server:
  port: 8071

spring:
  application:
    name: star-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///star?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 852000
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect