server:
  port: 8091

spring:
  application:
    name: star-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///star?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 852000
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

eureka: #注册中心配置
  instance:
    prefer-ip-address: true
  client: #客户端配置
    register-with-eureka: true      #是否注册当前服务
    fetch-registry: true            #是否缓存服务列表
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka #注册中心地址
star-product:                       #负载均衡算法
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
      ReadTimeout: 5000             # feign调用的超时时间，feign底层使用了ribbon来完成负载均衡

feign:
  client:
    config:
      star-product:                 # 服务提供者的名字
        loggerLevel: FULL           # NONE BASIC HEADERS FULL
  hystrix:                          #启用断路器，改配置仅适用于远程调用
    enabled: true

hystrix: #断路器超时配置
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
  level:
    com.zrx.springCloud.service.IProductService: debug